#!/bin/sh
set -e
PACKAGE='events-to-array'
SEDCMD="s,require\s*[(]\s*'[.][.][^)']*['][)],require('$PACKAGE'),g"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

mkdir $tmpdir/test
cd module-events-to-array
find test -name '*.js' -print0 | \
    xargs -0 -n1  \
	  sh -c 'set -e; echo "TESTING: $3"; sed $1 < $3 > $2/$3' sedtape "$SEDCMD" "$tmpdir"

cd $tmpdir
tap test/*.js
