#!/bin/sh
set -e
PACKAGE='tap-parser'
SEDCMD="s,require\s*[(]\s*'[.][.]/\([^']*\)'\s*[)],require('$PACKAGE/'\1),g"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

mkdir $tmpdir/test
find test/ -name '*.js' -print0 | \
    xargs -0 -n1  \
	  sh -c 'set -e; echo "TESTING: $3"; sed $1 < $3 > $2/$3' sedtape "$SEDCMD" "$tmpdir"

cd $tmpdir
tap test/*.js
